// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPJGeFy4WZi6ULHyoS_xnMSk4EqTJhIYk',
    appId: '1:516870987269:web:aaf0f72e355e2c66e1866c',
    messagingSenderId: '516870987269',
    projectId: 'nagibpay',
    authDomain: 'nagibpay.firebaseapp.com',
    databaseURL: 'https://nagibpay-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nagibpay.appspot.com',
    measurementId: 'G-RMFXX5FBBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR1KlpzrF46j5ezvf2ayEyFLfgfKaDjlg',
    appId: '1:516870987269:android:258c5c00bd5cf1fbe1866c',
    messagingSenderId: '516870987269',
    projectId: 'nagibpay',
    databaseURL: 'https://nagibpay-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nagibpay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8xv1S1XFdAij7uwR2l50MmO3ynYrgSqo',
    appId: '1:516870987269:ios:d614ed4a3e4b6a79e1866c',
    messagingSenderId: '516870987269',
    projectId: 'nagibpay',
    databaseURL: 'https://nagibpay-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nagibpay.appspot.com',
    iosClientId: '516870987269-no2mp6egv2v3vhdvik5csdcukoo5g4at.apps.googleusercontent.com',
    iosBundleId: 'com.nagib.pay',
  );
}
